# Generated by Django 3.0.8 on 2020-07-30 22:00

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_size', models.CharField(choices=[('1 - 10', '1 - 10'), ('11 - 50', '11 - 50'), ('51 - 100', '51 - 100'), ('101 - 500', '101 - 500'), ('501 - 1000', '501 - 1000'), ('Above 1000', 'Above 1000')], default='1', max_length=10)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
    ]
