# Generated by Django 3.0.8 on 2020-07-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='organisation_sector',
            field=models.CharField(choices=[('AGRICULTURE', 'AGRICULTURE'), ('AVIATION', 'AVIATION'), ('COMMERCIAL/RETAIL', 'COMMERCIAL/RETAIL'), ('CONSTRUCTION', 'CONSTRUCTION'), ('EDUCATION AND TRAINING', 'EDUCATION AND TRAINING'), ('ENERGY AND POWER GENERATION', 'ENERGY AND POWER GENERATION'), ('FMCG', 'FMCG'), ('FASHION', 'FASHION'), ('FINANCIAL SERVICES', 'FINANCIAL SERVICES'), ('HAULAGE/LOGISTICS', 'HAULAGE/LOGISTICS'), ('HEALTHCARE', 'HEALTHCARE'), ('ICT', 'ICT'), ('MANUFACTURING', 'MANUFACTURING'), ('MEDIA & ENTERTAINMENT', 'MEDIA & ENTERTAINMENT'), ('OIL & GAS', 'OIL & GAS'), ('PROFESSIONAL SERVICES', 'PROFESSIONAL SERVICES'), ('TELECOMMUNICATIONS', 'TELECOMMUNICATIONS'), ('TRANSPORTATION', 'TRANSPORTATION'), ('WASTE MANAGEMENT', 'WASTE MANAGEMENT')], default='1', max_length=40),
        ),
    ]
