# Generated by Django 3.1 on 2020-08-14 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mychannel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Channel',
            new_name='SetUpChannel',
        ),
    ]
